// <auto-generated />
using System;
using ClientLock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClientLock.Migrations
{
    [DbContext(typeof(ClientLockDbContext))]
    [Migration("20251206170351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientLock.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdentityUserId = "A-001"
                        },
                        new
                        {
                            Id = 2,
                            IdentityUserId = "A-002"
                        },
                        new
                        {
                            Id = 3,
                            IdentityUserId = "A-003"
                        },
                        new
                        {
                            Id = 4,
                            IdentityUserId = "C-001"
                        },
                        new
                        {
                            Id = 5,
                            IdentityUserId = "C-002"
                        });
                });

            modelBuilder.Entity("ClientLock.models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tom@clientlock.com",
                            FirstName = "Thomas",
                            Image = "https://example.com/agent1.jpg",
                            LastName = "Riley",
                            Phone = "6151112222",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sarah@clientlock.com",
                            FirstName = "Sarah",
                            Image = "https://example.com/agent2.jpg",
                            LastName = "Nguyen",
                            Phone = "6153334444",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike@clientlock.com",
                            FirstName = "Mike",
                            Image = "https://example.com/agent3.jpg",
                            LastName = "Jordan",
                            Phone = "6155556666",
                            UserProfileId = 3
                        });
                });

            modelBuilder.Entity("ClientLock.models.AgentLawPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("LawPracticeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AgentLawPractices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            LawPracticeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            LawPracticeId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 2,
                            LawPracticeId = 2
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 2,
                            LawPracticeId = 3
                        },
                        new
                        {
                            Id = 5,
                            AgentId = 3,
                            LawPracticeId = 3
                        },
                        new
                        {
                            Id = 6,
                            AgentId = 3,
                            LawPracticeId = 4
                        });
                });

            modelBuilder.Entity("ClientLock.models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Email = "gerold@gmail.com",
                            FirstName = "Gerold",
                            LastName = "Green",
                            Phone = "6157778888",
                            UserProfileId = 4
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 2,
                            Email = "amanda@gmail.com",
                            FirstName = "Amanda",
                            LastName = "Parker",
                            Phone = "6159990000",
                            UserProfileId = 5
                        });
                });

            modelBuilder.Entity("ClientLock.models.LawPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LawPractices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Divorce and custody",
                            Type = "Family Law"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Criminal cases",
                            Type = "Criminal Defense"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Accident claims",
                            Type = "Personal Injury"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Wills and trusts",
                            Type = "Estate Planning"
                        });
                });

            modelBuilder.Entity("ClientLock.models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsultingOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LawPracticeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeetingTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            ClientId = 1,
                            ConsultingOn = "DUI charge",
                            LawPracticeId = 2,
                            MeetingTime = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "AgentRole1",
                            Name = "Agent",
                            NormalizedName = "Agent"
                        },
                        new
                        {
                            Id = "ClientRole1",
                            Name = "Client",
                            NormalizedName = "Client"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "A-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4f11026-7431-423b-b8e6-357df0f41f17",
                            Email = "tom@clientlock.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKJRHaO5YBAWJs1FCVf3ce+AiikVkEx3e10Fi5kAlGPefPWM2XXP+06/aJROzfHtwg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18a8d9ee-c48a-4fdb-9bb6-9424ac28dca6",
                            TwoFactorEnabled = false,
                            UserName = "TomRLaw"
                        },
                        new
                        {
                            Id = "A-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d758c80-b8ae-4104-a9dd-19a687d65a17",
                            Email = "sarah@clientlock.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEM78ruK1wz9PLNWbEkpkEbMVZ6WVzBHeZee33zViaNblk9EqoOvQemSZVnbbQbp45w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1122666c-71d0-41ed-bd02-c51173500c60",
                            TwoFactorEnabled = false,
                            UserName = "SarahLaw"
                        },
                        new
                        {
                            Id = "A-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef7d3dbc-cf3e-49bb-ab76-924c52daf580",
                            Email = "mike@clientlock.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHVufU5Q7kg96UCxTWJESahdUn/WgtqfBDPOX5+V+MSj25ks9uELfxiG2JTyscRj3g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1b876ac0-02e8-41da-a082-f15cf1443e2d",
                            TwoFactorEnabled = false,
                            UserName = "MikeLaw"
                        },
                        new
                        {
                            Id = "C-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0c28017-f229-44d8-b53f-161abef06cfc",
                            Email = "gerold@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHGejhgqpvGOFoprsd/ONfSz6kpltI1jw+5BKMmPTnVrUp3OSA1FzXW59FpH6Rd5kQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92392257-28e5-4b9f-8722-90a068157b80",
                            TwoFactorEnabled = false,
                            UserName = "GeroldG"
                        },
                        new
                        {
                            Id = "C-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c44dac47-df68-4fe9-9e70-a81114a38e80",
                            Email = "amanda@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKIs6Do3fy5hJSr9yh8636vpqiWHZk8bldZ74prkYAVixetGWf4OoD43yHSte6A+mQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb4fe1a1-4d17-452b-a230-ef02e5aa7e54",
                            TwoFactorEnabled = false,
                            UserName = "AmandaP"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "A-001",
                            RoleId = "AgentRole1"
                        },
                        new
                        {
                            UserId = "A-002",
                            RoleId = "AgentRole1"
                        },
                        new
                        {
                            UserId = "A-003",
                            RoleId = "AgentRole1"
                        },
                        new
                        {
                            UserId = "C-001",
                            RoleId = "ClientRole1"
                        },
                        new
                        {
                            UserId = "C-002",
                            RoleId = "ClientRole1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClientLock.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
