// <auto-generated />
using System;
using ClientLock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClientLock.Migrations
{
    [DbContext(typeof(ClientLockDbContext))]
    [Migration("20251216220650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientLock.models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tom@clientlock.com",
                            FirstName = "Thomas",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs10cupyp3Wf-pZvdPjGQuKne14ngVZbYdDQ&s",
                            LastName = "Riley",
                            Phone = "6151112222",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "sarah@clientlock.com",
                            FirstName = "Sarah",
                            Image = "https://images.squarespace-cdn.com/content/v1/5ec689480cc22c2d441e152f/9cbf4e0b-926f-431b-b27a-11c5ac3bd8df/corporate-headshots-professional-photography-connecticut-ct-photo-studio-nlalor-what-to-wear-women.jpg",
                            LastName = "Nguyen",
                            Phone = "6153334444",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike@clientlock.com",
                            FirstName = "Mike",
                            Image = "https://images.squarespace-cdn.com/content/v1/66a4f1fc404ca05cac7d8ec8/eb06ba09-879c-4da9-b4ea-ee0909600e54/Professional+Headshots+Male",
                            LastName = "Jordan",
                            Phone = "6155556666",
                            UserProfileId = 3
                        });
                });

            modelBuilder.Entity("ClientLock.models.AgentLawPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("LawPracticeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("LawPracticeId");

                    b.ToTable("AgentLawPractices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            LawPracticeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            LawPracticeId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 2,
                            LawPracticeId = 2
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 2,
                            LawPracticeId = 3
                        },
                        new
                        {
                            Id = 5,
                            AgentId = 3,
                            LawPracticeId = 3
                        },
                        new
                        {
                            Id = 6,
                            AgentId = 3,
                            LawPracticeId = 4
                        });
                });

            modelBuilder.Entity("ClientLock.models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Email = "gerold@gmail.com",
                            FirstName = "Gerold",
                            LastName = "Green",
                            Phone = "6157778888",
                            UserProfileId = 4
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 2,
                            Email = "amanda@gmail.com",
                            FirstName = "Amanda",
                            LastName = "Parker",
                            Phone = "6159990000",
                            UserProfileId = 5
                        });
                });

            modelBuilder.Entity("ClientLock.models.LawPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LawPractices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Divorce and custody",
                            Type = "Family Law"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Criminal cases",
                            Type = "Criminal Defense"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Accident claims",
                            Type = "Personal Injury"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Wills and trusts",
                            Type = "Estate Planning"
                        });
                });

            modelBuilder.Entity("ClientLock.models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsultingOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LawPracticeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeetingTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            ClientId = 1,
                            ConsultingOn = "DUI charge",
                            LawPracticeId = 2,
                            MeetingTime = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ClientLock.models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            ClientId = 0,
                            IdentityUserId = "A-001"
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 2,
                            ClientId = 0,
                            IdentityUserId = "A-002"
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 3,
                            ClientId = 0,
                            IdentityUserId = "A-003"
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 0,
                            ClientId = 1,
                            IdentityUserId = "C-001"
                        },
                        new
                        {
                            Id = 5,
                            AgentId = 0,
                            ClientId = 2,
                            IdentityUserId = "C-002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "AgentRole1",
                            Name = "AGENT",
                            NormalizedName = "Agent"
                        },
                        new
                        {
                            Id = "ClientRole1",
                            Name = "CLIENT",
                            NormalizedName = "Client"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "A-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be27cc22-47bf-4120-a763-e0e2e539a0a1",
                            Email = "tom@clientlock.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMZ1zUHEovTzirmrldp3+ISwgtDGgU3kwTLvl2/yOXjnFnZht/SkVF5gQ2eW35mZpQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dbef25ba-4f97-4c80-ae0a-d3169e41e693",
                            TwoFactorEnabled = false,
                            UserName = "TomRLaw"
                        },
                        new
                        {
                            Id = "A-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81159a3d-691f-40e4-bc97-21d901df00a8",
                            Email = "sarah@clientlock.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELsqpIjufOid8N1Krbd791u/sOshQON9HHTXFdHLHcOQV4KMvrgNFRDmmVm3y4l0SQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97189f2e-c805-4598-9be0-dfd3fa45d269",
                            TwoFactorEnabled = false,
                            UserName = "SarahLaw"
                        },
                        new
                        {
                            Id = "A-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "228806f2-ad33-49ed-8e7e-1fd3677ee39e",
                            Email = "mike@clientlock.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEP28vXC1idQqf3gAe9QWDbvBQOJy6EkmXcluxj67s59iBqXFnbVX7xFtSaqhGDh1uw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "acca7c1b-a1d2-4e02-aa94-eaa9ce7086ae",
                            TwoFactorEnabled = false,
                            UserName = "MikeLaw"
                        },
                        new
                        {
                            Id = "C-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26ad0f69-0ff3-4dc1-a56c-cc284f2af82e",
                            Email = "gerold@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHPX7gf5+lrP8pAUhCVcgANXG+CwvHXJSH1xXSJalNVxzcCdy/4RECbHDSVckx1GeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "51626e79-023a-4b70-9f81-d59e6e0592e9",
                            TwoFactorEnabled = false,
                            UserName = "GeroldG"
                        },
                        new
                        {
                            Id = "C-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2ed127a-fb9a-42fe-88fb-a039b17c0b8c",
                            Email = "amanda@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ5fTYYkzTpTwnjXPTqLL+AMIk+EN4NHfVmork25S3ZK4S8zIvWPKIg9Of3fGZag/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4afc539f-0404-4da7-af1e-19deccdb2bbf",
                            TwoFactorEnabled = false,
                            UserName = "AmandaP"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "A-001",
                            RoleId = "AgentRole1"
                        },
                        new
                        {
                            UserId = "A-002",
                            RoleId = "AgentRole1"
                        },
                        new
                        {
                            UserId = "A-003",
                            RoleId = "AgentRole1"
                        },
                        new
                        {
                            UserId = "C-001",
                            RoleId = "ClientRole1"
                        },
                        new
                        {
                            UserId = "C-002",
                            RoleId = "ClientRole1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClientLock.models.AgentLawPractice", b =>
                {
                    b.HasOne("ClientLock.models.Agent", "Agent")
                        .WithMany("AgentLawPractices")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientLock.models.LawPractice", "LawPractice")
                        .WithMany()
                        .HasForeignKey("LawPracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("LawPractice");
                });

            modelBuilder.Entity("ClientLock.models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientLock.models.Agent", b =>
                {
                    b.Navigation("AgentLawPractices");
                });
#pragma warning restore 612, 618
        }
    }
}
